/**
 * 遊戲角色/描述 (Roles & desc) 清單
 */
window.OFFICIAL_ROLES_CATALOG = [
  // 藍/紅隊核心角色 (Blue,red)
  { id: 'pres', name: '總統 (President)', team: 'blue', icon: '👔', desc: '你必須遠離「炸彈客」！遊戲結束時，若與「炸彈客」在不同房間則藍隊獲勝。', pairs: 'bomb' },
  { id: 'bomb', name: '炸彈客 (Bomber)', team: 'red', icon: '💣', desc: '你必須炸死「總統」！遊戲結束時引爆炸彈，使你所在的房間內所有人死亡，若與「總統」在同一個房間則紅隊獲勝。', pairs: 'pres' },
  { id: 'pres_d', name: '總統女兒 (President\'s Daughter)', team: 'blue', icon: '👧', desc: '妳是「總統」備選人，若「總統」被埋葬或離開遊戲時，妳必須肩負起「總統」的責任。', pairs: 'martyr' },
  { id: 'martyr', name: '烈士 (Martyr)', team: 'red', icon: '🔥', desc: '你是「炸彈客」備選人，若「炸彈客」被埋葬或離開遊戲你必須肩負起「炸彈客」的責任。', pairs: 'pres_d' },
  { id: 'blue_drone', name: '藍色無人機 (Blue Drone)', team: 'blue', icon: '🛸', desc: '你必須摧毀「紅色鐵拳」！遊戲結束時若與「紅色鐵拳」身處同一個房間，則藍隊獲勝。', pairs: 'red_fist,judge' },
  { id: 'red_fist', name: '紅色鐵拳 (Red Fist)', team: 'red', icon: '🥊', desc: '你必須遠離「藍色無人機」！。遊戲結束時若與「藍色無人機」身處不同房間，則紅隊獲勝。', pairs: 'blue_drone,judge' },
  { id: 'blue_firecracker', name: '藍色爆竹 (Blue Firecracker)', team: 'blue', icon: '🧨', desc: '「藍色無人機」的替補角色。若「藍色無人機」被埋牌或移出遊戲，你必須肩負起「藍色無人機」的責任。', pairs: 'red_foot' },
  { id: 'red_foot', name: '紅色鐵足 (Red Foot)', team: 'red', icon: '👢', desc: '「紅色鐵拳」的替補角色。若「紅色鐵拳」被埋牌或移出遊戲，你必須肩負起「紅色鐵拳」的責任。', pairs: 'blue_firecracker' },
  { id: 'doctor', name: '醫生 (Doctor)', team: 'blue', icon: '🩺', desc: '遊戲結束前，你必須與「總統」進行過『角色分享』，否則藍隊強制失敗。', pairs: 'engineer,judge' },
  { id: 'engineer', name: '工程師 (Engineer)', team: 'red', icon: '⚙️', desc: '遊戲結束前，你必須與「炸彈客」進行過『角色分享』，否則紅隊強制失敗。', pairs: 'doctor,judge' },
  { id: 'nurse', name: '護士 (Nurse)', team: 'blue', icon: '💉', desc: '你是「醫生」備選人，若「醫生」被埋葬或離開遊戲時，你必須承擔「醫生」的職責。', pairs: 'tinkerer' },
  { id: 'tinkerer', name: '工匠 (Tinkerer)', team: 'red', icon: '🔨', desc: '你是「工程師」備選人，若「工程師」被埋葬或離開遊戲時，你必須承擔「工程師」的職責。', pairs: 'nurse' },
  { id: 'firefighter', name: '消防員 (Firefighter)', team: 'blue', icon: '🧑‍🚒', desc: '與「總統」進行『角色分享』賦予"防火"狀態，「總統」所在的房間免受燃燒波及，使該房間不受"燃火"狀態影響而死亡。', pairs: 'pyrotech,judge' }, 
  { id: 'pyrotech', name: '煙火專家 (Pyrotech)', team: 'red', icon: '🎆', desc: '與「炸彈客」進行『角色分享』賦予"燃火"狀態；「炸彈客」爆炸時引發燃燒，使另一間房間的玩家也會死亡。', pairs: 'firefighter,judge' }, 
  { id: 'spy_r', name: '紅隊間諜 (Red Spy)', team: 'blue', icon: '🕵️‍♀️', desc: '屬於紅隊但卡片底色為藍色；可以誤導他人『顏色分享』與『顏色揭露』的結果，請對紅隊忠誠！', pairs: 'spy_b' },
  { id: 'spy_b', name: '藍隊間諜 (Blue Spy)', team: 'red', icon: '🕵️‍♂️', desc: '屬於藍隊但卡片底色為紅色；可以誤導他人『顏色分享』與『顏色揭露』的結果，請對藍隊忠誠！', pairs: 'spy_r' },
  
  // 藍/紅隊普通成員 (Blue,red)
  { id: 'blue_mem', name: '藍隊成員 (Blue Team)', team: 'blue', icon: '🔵', desc: '保護「總統」安全，不要讓「總統」與「炸彈客」在同一個房間！', pairs: 'red_mem' },
  { id: 'red_mem', name: '紅隊成員 (Red Team)', team: 'red', icon: '🔴', desc: '協助「炸彈客」，讓「炸彈客」與「總統」在同一個房間引爆！', pairs: 'blue_mem' },

  // 藍/紅隊自帶狀態類 (Blue,red)
  { id: 'shy_b', name: '害羞小子 (Shy Guy)', team: 'blue', icon: '🙈', desc: '自帶"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』，"害羞"可被心理醫生治癒。', pairs: 'shy_r' },
  { id: 'shy_r', name: '害羞小子 (Shy Guy)', team: 'red', icon: '🙈', desc: '自帶"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』，"害羞"可被心理醫生治癒。', pairs: 'shy_b' },
  { id: 'coy_b', name: '靦腆少年 (Coy Boy)', team: 'blue', icon: '😳', desc: '自帶"靦腆"狀態：只能進行『顏色分享』，無法進行『角色分享』或任何揭露行為，"靦腆"可被心理醫生治癒。', pairs: 'coy_r' },
  { id: 'coy_r', name: '靦腆少年 (Coy Boy)', team: 'red', icon: '😳', desc: '自帶"靦腆"狀態：只能進行『顏色分享』，無法進行『角色分享』或任何揭露行為，"靦腆"可被心理醫生治癒。', pairs: 'coy_b' },
  { id: 'paranoid_b', name: '妄想者 (Paranoid)', team: 'blue', icon: '👀', desc: '自帶"妄想"狀態：整場遊戲只能進行一次『角色分享』，"妄想"可被心理醫生治癒。', pairs: 'paranoid_r' },
  { id: 'paranoid_r', name: '妄想者 (Paranoid)', team: 'red', icon: '👀', desc: '自帶"妄想"狀態：整場遊戲只能進行一次『角色分享』，"妄想"可被心理醫生治癒。', pairs: 'paranoid_b' },
  { id: 'fool_b', name: '傻瓜 (Fool)', team: 'blue', icon: '🤪', desc: '自帶"愚蠢"狀態：不能拒絕任何『角色分享』或『顏色分享』。', pairs: 'fool_r' },
  { id: 'fool_r', name: '傻瓜 (Fool)', team: 'red', icon: '🤪', desc: '自帶"愚蠢"狀態：不能拒絕任何『角色分享』或『顏色分享』。', pairs: 'fool_b' },
  { id: 'negotiator_b', name: '談判專家 (Negotiator)', team: 'blue', icon: '🤝', desc: '自帶"精明"狀態：只能進行『角色分享』，禁止『顏色分享』或任何揭露行為。', pairs: 'negotiator_r' },
  { id: 'negotiator_r', name: '談判專家 (Negotiator)', team: 'red', icon: '🤝', desc: '自帶"精明"狀態：只能進行『角色分享』，禁止『顏色分享』或任何揭露行為。', pairs: 'negotiator_b' },
  { id: 'exhibitionist_b', name: '露體狂 (Exhibitionist)', team: 'blue', icon: '🥼', desc: '自帶"裸露"狀態：只能進行『公開角色』，無法進行任何『分享』或『揭露』。', pairs: 'exhibitionist_r' },
  { id: 'exhibitionist_r', name: '露體狂 (Exhibitionist)', team: 'red', icon: '🥼', desc: '自帶"裸露"狀態：只能進行『公開角色』，無法進行任何『分享』或『揭露』。', pairs: 'exhibitionist_b' },
  { id: 'immunologist_b', name: '免疫者 (Immunologist)', team: 'blue', icon: '💊', desc: '自帶"免疫"狀態：任何角色的技能或狀態都對你完全無效，你可以拒絕一切要求。', pairs: 'immunologist_r' },
  { id: 'immunologist_r', name: '免疫者 (Immunologist)', team: 'red', icon: '💊', desc: '自帶"免疫"狀態：任何角色的技能或狀態都對你完全無效，你可以拒絕一切要求。', pairs: 'immunologist_b' },
  { id: 'seer_b', name: '先知 (Seer)', team: 'blue', icon: '🔮', desc: '自帶"通靈"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』；遊戲開始30秒內，先知可以透過技能查看所有玩家的角色。', pairs: 'seer_r' },
  { id: 'seer_r', name: '先知 (Seer)', team: 'red', icon: '🔮', desc: '自帶"通靈"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』；遊戲開始30秒內，先知可以透過技能查看所有玩家的角色。', pairs: 'seer_b' },

  // 藍/紅隊賦予狀態類 (Blue,red)
  { id: 'criminal_b', name: '罪犯 (Criminal)', team: 'blue', icon: '🦹🏻‍♀️', desc: '與你進行『角色分享』的玩家獲得"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』，"害羞"可被心理醫生治癒。', pairs: 'criminal_r' },
  { id: 'criminal_r', name: '罪犯 (Criminal)', team: 'red', icon: '🦹🏻‍♀️', desc: '與你進行『角色分享』的玩家獲得"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』，"害羞"可被心理醫生治癒。', pairs: 'criminal_b' },
  { id: 'thug_b', name: '暴徒 (Thug)', team: 'blue', icon: '✊', desc: '與你進行『角色分享』的玩家獲得"靦腆"狀態：只能進行『顏色分享』，無法進行『角色分享』或任何揭露行為，"靦腆"可被心理醫生治癒。', pairs: 'thug_r' },
  { id: 'thug_r', name: '暴徒 (Thug)', team: 'red', icon: '✊', desc: '與你進行『角色分享』的玩家獲得"靦腆"狀態：只能進行『顏色分享』，無法進行『角色分享』或任何揭露行為，"靦腆"可被心理醫生治癒。', pairs: 'thug_b' },
  { id: 'dealer_b', name: '荷官 (Dealer)', team: 'blue', icon: '🎴', desc: '與你進行『角色分享』的玩家獲得"愚蠢"狀態：不能拒絕任何『角色分享』或『顏色分享』。', pairs: 'dealer_r' },
  { id: 'dealer_r', name: '荷官 (Dealer)', team: 'red', icon: '🎴', desc: '與你進行『角色分享』的玩家獲得"愚蠢"狀態：不能拒絕任何『角色分享』或『顏色分享』。', pairs: 'dealer_b' },
  { id: 'professor_b', name: '教授 (Professor)', team: 'blue', icon: '🎓', desc: '任何與你進行『角色分享』者獲得"精明"狀態：之後只能進行『角色分享』。', pairs: 'professor_r' },
  { id: 'professor_r', name: '教授 (Professor)', team: 'red', icon: '🎓', desc: '任何與你進行『角色分享』者獲得"精明"狀態：之後只能進行『角色分享』。', pairs: 'professor_b' },
  { id: 'werewolf_b', name: '狼人 (Werewolf)', team: 'blue', icon: '🐺', desc: '進行『角色分享』或『顏色分享』會施加"咬傷"狀態：被咬者必須如實回答狼人問題。', pairs: 'werewolf_r' },
  { id: 'werewolf_r', name: '狼人 (Werewolf)', team: 'red', icon: '🐺', desc: '進行『角色分享』或『顏色分享』會施加"咬傷"狀態：被咬者必須如實回答狼人問題。', pairs: 'werewolf_b' },
  { id: 'gorgon_b', name: '蛇髮女妖 (Gorgon)', team: 'blue', icon: '🐍', desc: '進行『角色分享』時賦予對方"石化"狀態：使對方在進行領袖投票時須將雙臂垂下並喪失投票權。', pairs: 'gorgon_r' },
  { id: 'gorgon_r', name: '蛇髮女妖 (Gorgon)', team: 'red', icon: '🐍', desc: '進行『角色分享』時賦予對方"石化"狀態：使對方在進行領袖投票時須將雙臂垂下並喪失投票權。', pairs: 'gorgon_b' },
  { id: 'centipede_b', name: '人形蜈蚣 (Centipede)', team: 'blue', icon: '🐛', desc: '與你進行『角色分享』者獲得"連結"狀態：若"連結"者與你在不同房間則他必須『公開角色』。', pairs: 'centipede_r' },
  { id: 'centipede_r', name: '人形蜈蚣 (Centipede)', team: 'red', icon: '🐛', desc: '與你進行『角色分享』者獲得"連結"狀態：若"連結"者與你在不同房間則他必須『公開角色』。', pairs: 'centipede_b' },
  { id: 'piper_b', name: '吹笛人 (Piper)', team: 'blue', icon: '🪈', desc: '與非同隊陣營的玩家進行『角色分享』時，賦予對方"盲從"狀態：遊戲結束時，若"盲從"者與你在不同房間則他強制視為失敗。', pairs: 'piper_r' },
  { id: 'piper_r', name: '吹笛人 (Piper)', team: 'red', icon: '🪈', desc: '與非同隊陣營的玩家進行『角色分享』時，賦予對方"盲從"狀態：遊戲結束時，若"盲從"者與你在不同房間則他強制視為失敗。', pairs: 'piper_b' },
  { id: 'vampire_b', name: '吸血鬼 (Vampire)', team: 'blue', icon: '🧛', desc: '與非同隊陣營的玩家進行『角色分享』時賦予"誘惑"狀態：對方必須服從你的指示來使用角色技能與領袖投票。', pairs: 'vampire_r' },
  { id: 'vampire_r', name: '吸血鬼 (Vampire)', team: 'red', icon: '🧛', desc: '與非同隊陣營的玩家進行『角色分享』時賦予"誘惑"狀態：對方必須服從你的指示來使用角色技能與領袖投票。', pairs: 'vampire_b' },
  { id: 'hypnotist_b', name: '催眠師 (Hypnotist)', team: 'blue', icon: '🌀', desc: '進行『角色分享』時對其施加"催眠"狀態：強制對方在行為上必須扮演你指定的角色(盲人、小丑、默劇演員、木乃伊)。', pairs: 'hypnotist_r' },
  { id: 'hypnotist_r', name: '催眠師 (Hypnotist)', team: 'red', icon: '🌀', desc: '進行『角色分享』時對其施加"催眠"狀態：強制對方在行為上必須扮演你指定的角色(盲人、小丑、默劇演員、木乃伊)。', pairs: 'hypnotist_b' },
  { id: 'conspirator_b', name: '共謀者 (Conspirator)', team: 'blue', icon: '🗡️', desc: '與非同隊陣營的玩家進行『角色分享』時，對其施加"叛徒"狀態：使其獲勝目標倒戈向你的隊伍。', pairs: 'conspirator_r' },
  { id: 'conspirator_r', name: '共謀者 (Conspirator)', team: 'red', icon: '🗡️', desc: '與非同隊陣營的玩家進行『角色分享』時，對其施加"叛徒"狀態：使其獲勝目標倒戈向你的隊伍。', pairs: 'conspirator_b' },
  //{ id: 'psychologist_b', name: '心理醫生 (Psychologist)', team: 'blue', icon: '🛋️', desc: '進行『角色揭露』給"害羞"或"靦腆"或"妄想"玩家時，對方可與你『角色分享』並治癒移除這些狀態。', pairs: 'psychologist_r' },
  //{ id: 'psychologist_r', name: '心理醫生 (Psychologist)', team: 'red', icon: '🛋️', desc: '進行『角色揭露』給"害羞"或"靦腆"或"妄想"玩家時，對方可與你『角色分享』並治癒移除這些狀態。', pairs: 'psychologist_b' },
  //{ id: 'loyalist_b', name: '效忠者 (Loyalist)', team: 'blue', icon: '🛡️', desc: '免疫"叛徒"狀態，且能透過『角色分享』消除他人身上的"叛徒"狀態。', pairs: 'loyalist_r' },
  //{ id: 'loyalist_r', name: '效忠者 (Loyalist)', team: 'red', icon: '🛡️', desc: '免疫"叛徒"狀態，且能透過『角色分享』消除他人身上的"叛徒"狀態。', pairs: 'loyalist_b' },
  //{ id: 'medic_b', name: '醫療兵 (Medic)', team: 'blue', icon: '🏥', desc: '與你進行『角色分享』的玩家清除身上額外狀態，不包含角色本身自帶的狀態以及"叛徒"狀態。', pairs: 'medic_r' },
  //{ id: 'medic_r', name: '醫療兵 (Medic)', team: 'red', icon: '🏥', desc: '與你進行『角色分享』的玩家清除身上額外狀態，不包含角色本身自帶的狀態以及"叛徒"狀態。', pairs: 'medic_b' },
  
  // 藍/紅隊卡牌資訊類 (Blue,red)
  { id: 'agent_b', name: '特務 (Agent)', team: 'blue', icon: '🕶️', desc: '每回合只能用一次，可找一名玩家進行『角色揭露』，強制對方與你進行『角色分享』，無法拒絕。', pairs: 'agent_r' },
  { id: 'agent_r', name: '特務 (Agent)', team: 'red', icon: '🕶️', desc: '每回合只能用一次，可找一名玩家進行『角色揭露』，強制對方與你進行『角色分享』，無法拒絕。', pairs: 'agent_b' },
  { id: 'interrogator_b', name: '審訊官 (Interrogator)', team: 'blue', icon: '🔦', desc: '每回合只能用一次，向對方進行『角色揭露』並詢問一個是非題，對方必須誠實作答。', pairs: 'interrogator_r' },
  { id: 'interrogator_r', name: '審訊官 (Interrogator)', team: 'red', icon: '🔦', desc: '每回合只能用一次，向對方進行『角色揭露』並詢問一個是非題，對方必須誠實作答。', pairs: 'interrogator_b' },
  { id: 'enforcer_b', name: '執法者 (Enforcer)', team: 'blue', icon: '📋', desc: '每回合只能用一次，向兩名玩家進行『角色揭露』，告訴他們「你們必須互相進行『角色分享』！」。', pairs: 'enforcer_r' },
  { id: 'enforcer_r', name: '執法者 (Enforcer)', team: 'red', icon: '📋', desc: '每回合只能用一次，向兩名玩家進行『角色揭露』，告訴他們「你們必須互相進行『角色分享』！」。', pairs: 'enforcer_b' },
  { id: 'bully_b', name: '惡霸 (Bully)', team: 'blue', icon: '😠', desc: '當有人同意與你進行『顏色分享』時，改為『角色揭露』，強制對方也必須『角色揭露』。', pairs: 'bully_r' },
  { id: 'bully_r', name: '惡霸 (Bully)', team: 'red', icon: '😠', desc: '當有人同意與你進行『顏色分享』時，改為『角色揭露』，強制對方也必須『角色揭露』。', pairs: 'bully_b' },
  //奪取卡牌的角色加機制 外星人 盜身魔 身分竊賊 獵人 異形獵手
  //{ id: 'alien_b', name: '外星人 (Alien)', team: 'blue', icon: '👽', desc: '進行『角色分享』時強行綁架扣留對方的卡牌，使其無法再向任何人亮牌。', pairs: 'alien_r' },
  //{ id: 'alien_r', name: '外星人 (Alien)', team: 'red', icon: '👽', desc: '進行『角色分享』時強行綁架扣留對方的卡牌，使其無法再向任何人亮牌。', pairs: 'alien_b' },
  //{ id: 'body_snatcher_b', name: '盜身魔 (Body Snatcher)', team: 'blue', icon: '🎭', desc: '進行『角色分享』時奪取對方卡牌作為假面展示，受害者失去卡牌但保有能力。', pairs: 'body_snatcher_r' },
  //{ id: 'body_snatcher_r', name: '盜身魔 (Body Snatcher)', team: 'red', icon: '🎭', desc: '進行『角色分享』時奪取對方卡牌作為假面展示，受害者失去卡牌但保有能力。', pairs: 'body_snatcher_b' },
  //{ id: 'identity_thief_b', name: '身分竊賊 (Identity Thief)', team: 'blue', icon: '👥', desc: '進行『角色分享』時奪取對方角色卡牌，並將自帶"害羞"狀態的身分竊賊交換給對方。"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』。', pairs: 'identity_thief_r' },
  //{ id: 'identity_thief_r', name: '身分竊賊 (Identity Thief)', team: 'red', icon: '👥', desc: '進行『角色分享』時奪取對方角色卡牌，並將自帶"害羞"狀態的身分竊賊交換給對方。"害羞"狀態：不能給別人看卡牌，無法進行任何『分享』或『揭露』。', pairs: 'identity_thief_b' },
  //加機制換成普通隊員 資本家 社會主義者 白隊成員 
  //{ id: 'capitalist', name: '資本家 (Capitalist)', team: 'blue', icon: '💰', desc: '每回合只能用一次，進行『角色分享』時，強迫對方將其角色卡牌換成「藍隊成員」。', pairs: 'socialist' },
  //{ id: 'socialist', name: '社會主義者 (Socialist)', team: 'red', icon: '🚩', desc: '每回合只能用一次，進行『角色分享』時，強迫對方將其角色卡牌換成「紅隊成員」。', pairs: 'capitalist' },
  //{ id: 'hunter_b', name: '獵人 (Hunter)', team: 'blue', icon: '🏹', desc: '若有非同隊陣營的玩家對你使用『角色分享』類的技能，你可以沒收其角色卡牌且不受其技能影響。', pairs: 'hunter_r' },
  //{ id: 'hunter_r', name: '獵人 (Hunter)', team: 'red', icon: '🏹', desc: '若有非同隊陣營的玩家對你使用『角色分享』類的技能，你可以沒收其角色卡牌且不受其技能影響。', pairs: 'hunter_b' },
  //{ id: 'informer_b', name: '告密者 (Informer)', team: 'blue', icon: '✉️', desc: '紅隊向你進行『角色揭露』時必須收下；終局若平手，收受卡牌較多的一隊判負。', pairs: 'informer_r' },
  //{ id: 'informer_r', name: '告密者 (Informer)', team: 'red', icon: '✉️', desc: '藍隊向你進行『角色揭露』時必須收下；終局若平手，收受卡牌較多的一隊判負。', pairs: 'informer_b' },
  { id: 'mad_scientist_b', name: '瘋狂科學家 (Mad Scientist)', team: 'blue', icon: '🧪', desc: '整場限一次，進行『角色揭露』給兩名玩家，強迫這兩名玩家強制互換角色卡牌。', pairs: 'mad_scientist_r' },
  { id: 'mad_scientist_r', name: '瘋狂科學家 (Mad Scientist)', team: 'red', icon: '🧪', desc: '整場限一次，進行『角色揭露』給兩名玩家，強迫這兩名玩家強制互換角色卡牌。', pairs: 'mad_scientist_b' },
  { id: 'paparazzo_b', name: '狗仔隊 (Paparazzo)', team: 'blue', icon: '📸', desc: '可以干擾玩家間的交談，可正大光明偷窺任何『分享』與『揭露』行為，但不可對他人動手動腳。', pairs: 'paparazzo_r' },
  { id: 'paparazzo_r', name: '狗仔隊 (Paparazzo)', team: 'red', icon: '📸', desc: '可以干擾玩家間的交談，可正大光明偷窺任何『分享』與『揭露』行為，但不可對他人動手動腳。', pairs: 'paparazzo_b' },
  
  // 藍/紅隊角色行為扮演類 (Blue,red)
  { id: 'angel_b', name: '天使 (Angel)', team: 'blue', icon: '👼', desc: '只能說實話，但不需要說出口的可以撒謊或隱瞞。', pairs: 'angel_r' },
  { id: 'angel_r', name: '天使 (Angel)', team: 'red', icon: '👼', desc: '只能說實話，但不需要說出口的可以撒謊或隱瞞。', pairs: 'angel_b' },
  { id: 'demon_b', name: '惡魔 (Demon)', team: 'blue', icon: '👿', desc: '只能說謊話，不需要說出口的可以不撒謊。', pairs: 'demon_r' },
  { id: 'demon_r', name: '惡魔 (Demon)', team: 'red', icon: '😈', desc: '只能說謊話，不需要說出口的可以不撒謊。', pairs: 'demon_b' },
  { id: 'mime_b', name: '默劇演員 (Mime)', team: 'blue', icon: '🤐', desc: '你只能用比手畫腳來表演，全場必須盡力保持不發出任何聲音。', pairs: 'mime_r' },
  { id: 'mime_r', name: '默劇演員 (Mime)', team: 'red', icon: '🤐', desc: '你只能用比手畫腳來表演，全場必須盡力保持不發出任何聲音。', pairs: 'mime_b' },
  { id: 'mummy_b', name: '木乃伊 (Mummy)', team: 'blue', icon: '🧻', desc: '你只能說[呃...]這個字來溝通。', pairs: 'mummy_r' },
  { id: 'mummy_r', name: '木乃伊 (Mummy)', team: 'red', icon: '🧻', desc: '你只能說[呃...]這個字來溝通。', pairs: 'mummy_b' },
  { id: 'doggy_b', name: '狗狗 (Doggy)', team: 'blue', icon: '🐶', desc: '你只能說[汪!]這個字來溝通。若你比敵方陣營的「狗狗」更快對「狗狗主人」進行『角色分享』，則「狗狗主人」的勝利條件會與你所屬的陣營一樣。', pairs: 'doggy_r,dog_owner' },
  { id: 'doggy_r', name: '狗狗 (Doggy)', team: 'red', icon: '🐶', desc: '你只能說[汪!]這個字來溝通。若你比敵方陣營的「狗狗」更快和「狗狗主人」進行『角色分享』，則「狗狗主人」的勝利條件會與你所屬的陣營一樣。', pairs: 'doggy_b,dog_owner' },
  { id: 'clown_b', name: '小丑 (Clown)', team: 'blue', icon: '🤡', desc: '你是一名帶來歡樂的小丑，在遊戲進行中必須盡全力保持微笑。', pairs: 'clown_r' },
  { id: 'clown_r', name: '小丑 (Clown)', team: 'red', icon: '🤡', desc: '你是一名帶來歡樂的小丑，在遊戲進行中必須盡全力保持微笑。', pairs: 'clown_b' },
  { id: 'loner_b', name: '邊緣人 (Loner)', team: 'blue', icon: '🫥', desc: '你現在很邊緣，在整場遊戲過程中必須站在角落不能移動，回合結束時你可以換一個角落。', pairs: 'blind_r' },
  { id: 'loner_r', name: '邊緣人 (Loner)', team: 'red', icon: '🫥', desc: '你現在很邊緣，在整場遊戲過程中必須站在角落不能移動，回合結束時你可以換一個角落。', pairs: 'blind_b' },
  { id: 'blind_b', name: '盲人 (Blind)', team: 'blue', icon: '🦯', desc: '你現在看不到了，在整場遊戲過程中必須盡力閉上雙眼。', pairs: 'blind_r' },
  { id: 'blind_r', name: '盲人 (Blind)', team: 'red', icon: '🦯', desc: '你現在看不到了，在整場遊戲過程中必須盡力閉上雙眼。', pairs: 'blind_b' },
 
  // 藍/紅隊房間移動類 (Blue,red)
  { id: 'security_b', name: '保安 (Security)', team: 'blue', icon: '👮', desc: '整場遊戲只能使用一次，你可以『公開角色』後指定一名同房玩家本輪不能作為人質離開房間。', pairs: 'security_r' },
  { id: 'security_r', name: '保安 (Security)', team: 'red', icon: '👮', desc: '整場遊戲只能使用一次，你可以『公開角色』後指定一名同房玩家本輪不能作為人質離開房間。', pairs: 'security_b' },
  { id: 'pirate_b', name: '海盜 (Pirate)', team: 'blue', icon: '🏴‍☠️', desc: '整場遊戲只能使用一次，你可以『公開角色』後強制指定房內一名玩家在本輪結束時必須作為人質換房。', pairs: 'pirate_r' },
  { id: 'pirate_r', name: '海盜 (Pirate)', team: 'red', icon: '🏴‍☠️', desc: '整場遊戲只能使用一次，你可以『公開角色』後強制指定房內一名玩家在本輪結束時必須作為人質換房。', pairs: 'pirate_b' },
  { id: 'kangaroo_b', name: '袋鼠 (Kangaroo)', team: 'blue', icon: '🦘', desc: '整場遊戲只能使用一次，你可以『公開角色』後跳至對面房間，並強制挑選對面房內一人踢回原房間。', pairs: 'kangaroo_r' },
  { id: 'kangaroo_r', name: '袋鼠 (Kangaroo)', team: 'red', icon: '🦘', desc: '整場遊戲只能使用一次，你可以『公開角色』後跳至對面房間，並強制挑選對面房內一人踢回原房間。', pairs: 'kangaroo_b' },
  { id: 'rat_b', name: '老鼠 (Rat)', team: 'blue', icon: '🐀', desc: '整場遊戲只能使用一次，你可以『公開角色』自己潛入對面房間，但必須在當輪結束前返回原房間。', pairs: 'rat_r' },
  { id: 'rat_r', name: '老鼠 (Rat)', team: 'red', icon: '🐀', desc: '整場遊戲只能使用一次，你可以『公開角色』自己潛入對面房間，但必須在當輪結束前返回原房間。', pairs: 'rat_b' },
  { id: 'cleaner_b', name: '清潔工 (Cleaner)', team: 'blue', icon: '🧹', desc: '整場遊戲只能使用一次，你可以『公開角色』選擇一名玩家可以潛入對面房間，必須在當輪結束前返回原房間。', pairs: 'cleaner_r' },
  { id: 'cleaner_r', name: '清潔工 (Cleaner)', team: 'red', icon: '🧹', desc: '整場遊戲只能使用一次，你可以『公開角色』選擇一名玩家可以潛入對面房間，必須在當輪結束前返回原房間。', pairs: 'cleaner_b' },
  { id: 'usurper_b', name: '篡位者 (Usurper)', team: 'blue', icon: '⚡', desc: '整場遊戲只能使用一次，你可以『公開角色』直接篡位成為該房間領袖。', pairs: 'usurper_r' },
  { id: 'usurper_r', name: '篡位者 (Usurper)', team: 'red', icon: '⚡', desc: '整場遊戲只能使用一次，你可以『公開角色』直接篡位成為該房間領袖。', pairs: 'usurper_b' },
  { id: 'gargoyle_b', name: '石像鬼 (Gargoyle)', team: 'blue', icon: '🗿', desc: '整場遊戲只能使用一次，被選為人質時，你可以『公開角色』大喊[俗頭!!!]並蹲下，之後都不能在被選為人質。', pairs: 'gargoyle_r' },
  { id: 'gargoyle_r', name: '石像鬼 (Gargoyle)', team: 'red', icon: '🗿', desc: '整場遊戲只能使用一次，被選為人質時，你可以『公開角色』大喊[俗頭!!!]並蹲下，之後都不能在被選為人質。', pairs: 'gargoyle_b' },
  { id: 'bouncer_b', name: '保鏢 (Bouncer)', team: 'blue', icon: '🚪', desc: '整場遊戲只能使用一次，房內人數多於對面時，你可以『公開角色』對著一名玩家大喊「滾出去!!!」使該玩家立刻更換房間。', pairs: 'bouncer_r' },
  { id: 'bouncer_r', name: '保鏢 (Bouncer)', team: 'red', icon: '🚪', desc: '整場遊戲只能使用一次，房內人數多於對面時，你可以『公開角色』對著一名玩家大喊「滾出去!!!」使該玩家立刻更換房間。', pairs: 'bouncer_b' },
  { id: 'tentaclese_b', name: '觸手怪 (Tentaclese)', team: 'blue', icon: '🐙', desc: '整場遊戲只能使用一次，房內人數少於對面時，你可以『公開角色』衝進對面房間抓住一名玩家拖回自己房間。', pairs: 'tentaclese_r' },
  { id: 'tentaclese_r', name: '觸手怪 (Tentaclese)', team: 'red', icon: '🐙', desc: '整場遊戲只能使用一次，房內人數少於對面時，你可以『公開角色』衝進對面房間抓住一名玩家拖回自己房間。', pairs: 'tentaclese_b' },
  { id: 'eris', name: '紛爭女神厄里斯 (Eris)', team: 'blue', icon: '⚡', desc: '整場遊戲只能使用一次，你可以向兩名玩家進行『角色揭露』，賦予他們"憎恨"狀態：兩人的勝利條件改為：結算時必須在不同房間才能獲勝。', pairs: 'cupid' },
  { id: 'cupid', name: '愛神丘比特 (Cupid)', team: 'red', icon: '💘', desc: '整場遊戲只能使用一次，你可以向兩名玩家進行『角色揭露』，賦予他們"相愛"狀態：兩人的勝利條件改為：結算時必須在同一房間才能獲勝。', pairs: 'eris' },
  { id: 'enlisted_b', name: '應徵者 (Enlisted)', team: 'blue', icon: '🎖️', desc: '整場遊戲只能使用一次，在最後一回合開始前，你可以『公開角色』後自己直接內定為本輪人質。', pairs: 'enlisted_r' },
  { id: 'enlisted_r', name: '應徵者 (Enlisted)', team: 'red', icon: '🎖️', desc: '整場遊戲只能使用一次，在最後一回合開始前，你可以『公開角色』後自己直接內定為本輪人質。', pairs: 'enlisted_b' },
  { id: 'ninja_b', name: '忍者 (Ninja)', team: 'blue', icon: '🥷', desc: '整場遊戲只能使用一次，在最後一回合開始前，你可以『公開角色』後衝入對面房間抓走一名玩家，雙方一同移出遊戲(離開遊戲場地)。', pairs: 'ninja_r' },
  { id: 'ninja_r', name: '忍者 (Ninja)', team: 'red', icon: '🥷', desc: '整場遊戲只能使用一次，在最後一回合開始前，你可以『公開角色』後衝入對面房間抓走一名玩家，雙方一同移出遊戲(離開遊戲場地)。', pairs: 'ninja_b' },
  { id: 'ambassador_b', name: '大使 (Ambassador)', team: 'blue', icon: '🕊️', desc: '你可以『公開角色』，你永久免疫所有技能且可以在回合進行時任意於兩房間走動，不能當人質也不算投票人數。', pairs: 'ambassador_r' },
  { id: 'ambassador_r', name: '大使 (Ambassador)', team: 'red', icon: '🕊️', desc: '你可以『公開角色』，你永久免疫所有技能且可以在回合進行時任意於兩房間走動，不能當人質也不算投票人數。', pairs: 'ambassador_b' },
  //{ id: 'time_lord_b', name: '時間領主 (Time Lord)', team: 'blue', icon: '⏳', desc: '整場遊戲只能使用一次，『公開角色』後。', pairs: 'time_lord_r' },
  //{ id: 'time_lord_r', name: '時間領主 (Time Lord)', team: 'red', icon: '⏳', desc: '整場遊戲只能使用一次，『公開角色』後。', pairs: 'time_lord_b' },
  
  // 藍/紅隊特殊行為類 (Blue,red)
  //{ id: 'trader_b', name: '走私商人 (Trader)', team: 'blue', icon: '📦', desc: '整場遊戲只能使用一次，你可以跟本局遊戲的埋葬卡互換，並繼承角色卡牌與勝利條件。', pairs: 'trader_r' },
  //{ id: 'trader_r', name: '走私商人 (Trader)', team: 'red', icon: '📦', desc: '整場遊戲只能使用一次，你可以跟本局遊戲的埋葬卡互換，並繼承角色卡牌與勝利條件。', pairs: 'trader_b' },
  //{ id: 'voyeur_b', name: '偷窺狂 (Voyeur)', team: 'blue', icon: '🫣', desc: '在遊戲過程中的任何時刻，皆可直接偷看本局遊戲的埋葬卡。', pairs: 'voyeur_r' },
  //{ id: 'voyeur_r', name: '偷窺狂 (Voyeur)', team: 'red', icon: '🫣', desc: '在遊戲過程中的任何時刻，皆可直接偷看本局遊戲的埋葬卡。', pairs: 'voyeur_b' },
  { id: 'mayor_b', name: '市長 (Mayor)', team: 'blue', icon: '🎩', desc: '投票選擇領隊時，你可以『公開角色』之後你的投票永遠算作兩票。', pairs: 'mayor_r' },
  { id: 'mayor_r', name: '市長 (Mayor)', team: 'red', icon: '🎩', desc: '投票選擇領隊時，你可以『公開角色』之後你的投票永遠算作兩票。', pairs: 'mayor_b' },
  { id: 'tues_knight', name: '星期二騎士 (Tuesday Knight)', team: 'blue', icon: '⚔️', desc: '若你與「炸彈客」進行了『角色分享』，房內除了「總統」以外，其他玩家包含自己立即死亡，請帶著「炸彈客」找到房主終止遊戲，藍隊直接獲勝。', pairs: 'dr_boom' },
  { id: 'dr_boom', name: '爆炸先生 (Dr. Boom)', team: 'red', icon: '💥', desc: '若你與「總統」進行了『角色分享』，房內所有玩家包含自己立即死亡，請帶著「總統」找到房主終止遊戲，紅隊直接獲勝。', pairs: 'tues_knight' },
  { id: 'rageaholic_b', name: '狂怒者 (Rageaholic)', team: 'blue', icon: '🤬', desc: '整場遊戲只能使用一次，當你的房間已經選完人質，且你所在的房間領袖已經在走廊等待對方領袖時，你可以『公開角色』並大喊咆哮[從1數到10]對方領袖仍未出來則直接獨自獲勝。', pairs: 'rageaholic_r' },
  { id: 'rageaholic_r', name: '狂怒者 (Rageaholic)', team: 'red', icon: '🤬', desc: '整場遊戲只能使用一次，當你的房間已經選完人質，且你所在的房間領袖已經在走廊等待對方領袖時，你可以『公開角色』並大喊咆哮[從1數到10]對方領袖仍未出來則直接獨自獲勝。', pairs: 'rageaholic_b' },
  //{ id: 'xenohunter', name: '異形獵手 (Xenohunter)', team: 'blue', icon: '🔫', desc: '可以對被「異形」寄生的藍隊玩家進行『角色揭露』，將你的卡與對方的「異形」卡牌移出遊戲，此舉動會讓你遺失卡牌而無法進行任何分享行為。', pairs: 'xenomorph' }, //可以考慮加機制
  //{ id: 'xenomorph', name: '異形 (Xenomorph)', team: 'red', icon: '👾', desc: '將你的卡牌寄生於首位進行『顏色分享』的藍隊玩家身上，此舉動會讓你遺失卡牌而無法進行任何分享行為，終局使該藍隊玩家所在房間全員死亡。', pairs: 'xenohunter' }, //可以考慮加機制
  { id: 'marshall', name: '法警 (Marshall)', team: 'blue', icon: '⭐', desc: '若與「獨臂人」完成『角色分享』，請帶著「獨臂人」找到房主終止遊戲，藍隊直接獲勝。', pairs: 'fugitive,one_armed_man,witness' }, 
  { id: 'fugitive', name: '逃犯 (Fugitive)', team: 'red', icon: '🏃', desc: '若與「法警」完成『角色分享』，請帶著「法警」找到房主終止遊戲，紅隊直接獲勝。', pairs: 'marshall,one_armed_man,witness' },
  { id: 'witness', name: '目擊證人 (Witness)', team: 'blue', icon: '👁️', desc: '若與「逃犯」完成『角色分享』，請帶著「逃犯」找到房主終止遊戲，藍隊直接獲勝。', pairs: 'fugitive,marshall,one_armed_man' }, 
  { id: 'one_armed_man', name: '獨臂人 (One-Armed Man)', team: 'red', icon: '🦾', desc: '若與「目擊證人」完成『角色分享』，請帶著「目擊證人」找到房主終止遊戲，紅隊直接獲勝。', pairs: 'marshall,fugitive,witness' }, 
  
  // 灰隊房間判定類 (Grey)
  { id: 'survivor', name: '倖存者 (Survivor)', team: 'grey', icon: '🧗', desc: '遊戲結束時，自己和「炸彈客」在不同房間時你也獲勝。', pairs: 'victim' }, 
  { id: 'victim', name: '受害者 (Victim)', team: 'grey', icon: '🎯', desc: '遊戲結束時，自己和「炸彈客」在同一個房間時你也獲勝。', pairs: 'survivor' },
  { id: 'rival', name: '競爭對手 (Rival)', team: 'grey', icon: '👔', desc: '遊戲結束時，自己和「總統」在不同房間時你也獲勝。', pairs: 'intern' },
  { id: 'intern', name: '實習生 (Intern)', team: 'grey', icon: '🎒', desc: '遊戲結束時，自己和「總統」在同一個房間時你也獲勝。', pairs: 'rival' },
  { id: 'ahab', name: '亞哈船長 (Ahab)', team: 'grey', icon: '⚓', desc: '遊戲結束時，「莫比」和「炸彈客」在同一個房間，而你在另一個房間時你也獲勝。', pairs: 'moby' },
  { id: 'moby', name: '白鯨莫比 (Moby)', team: 'grey', icon: '🐋', desc: '遊戲結束時，「亞哈」和「炸彈客」在同一個房間，而你在另一個房間時你也獲勝。', pairs: 'ahab' },
  { id: 'wife', name: '妻子 (Wife)', team: 'grey', icon: '💍', desc: '遊戲結束時，自己和「總統」在同一房間，「情婦」在不同房間時你也獲勝。', pairs: 'mistress' },
  { id: 'mistress', name: '情婦 (Mistress)', team: 'grey', icon: '💄', desc: '遊戲結束時，自己和「總統」在同一房間，「妻子」在不同房間時你也獲勝。', pairs: 'wife' },
  { id: 'butler', name: '管家 (Butler)', team: 'grey', icon: '🤵', desc: '遊戲結束時，自己和「總統」以及「女僕」在同一個房間時你也獲勝。', pairs: 'maid' },
  { id: 'maid', name: '女僕 (Maid)', team: 'grey', icon: '🧹', desc: '遊戲結束時，自己和「總統」以及「管家」在同一個房間時你也獲勝。', pairs: 'butler' },
  { id: 'romeo', name: '羅密歐 (Romeo)', team: 'grey', icon: '💌', desc: '遊戲結束時，自己和「炸彈客」以及「茱麗葉」在同一個房間時你也獲勝。', pairs: 'juliet' },
  { id: 'juliet', name: '茱麗葉 (Juliet)', team: 'grey', icon: '🥀', desc: '遊戲結束時，自己和「炸彈客」以及「羅密歐」在同一個房間時你也獲勝。', pairs: 'romeo' },
  { id: 'hero', name: '英雄 (Hero)', team: 'grey', icon: '🦸', desc: '遊戲結束時，自己與「總統」與「炸彈客」在同一個房間則你獨自獲勝。', pairs: 'villain' },
  { id: 'villain', name: '惡徒 (Villain)', team: 'grey', icon: '🦹', desc: '遊戲結束時，自己和「總統」在同一個房間，「炸彈客」在不同房間時你也獲勝。', pairs: 'hero' },
  { id: 'queen', name: '女王 (Queen)', team: 'grey', icon: '👸', desc: '遊戲結束時，「總統」與「炸彈客」在同一個房間，而你在另一個房間時你也獲勝。', pairs: 'stunt_double' },
  { id: 'stunt_double', name: '替身演員 (Stunt Double)', team: 'grey', icon: '🎬', desc: '遊戲結束時，自己和「炸彈客」在同一個房間，「總統」在不同房間時你也獲勝。', pairs: 'queen' },
  { id: 'father', name: '父親 (Father)', team: 'grey', icon: '👨', desc: '只能在第一回合使用，可以對兩名玩家進行『角色揭露』並賦予他們"孩子"狀態；遊戲結束時，若這兩名玩家和「總統」在同一房間則你也獲勝。', pairs: 'mother' },
  { id: 'mother', name: '母親 (Mother)', team: 'grey', icon: '👩', desc: '只能在第一回合使用，可以對兩名玩家進行『角色揭露』並賦予他們"孩子"狀態，遊戲結束時，若這兩名玩家和「炸彈客」在不同房間時你也獲勝。', pairs: 'father' },
  
  // 灰隊三角關係 (Grey)
  { id: 'rock', name: '石頭 (Rock)', team: 'grey', icon: '🪨', desc: '遊戲結束時，自己和「剪刀」在同一個房間，「布」在不同房間時你也獲勝。', pairs: 'paper,scissors' }, 
  { id: 'paper', name: '布 (Paper)', team: 'grey', icon: '📄', desc: '遊戲結束時，自己和「石頭」在同一個房間，「剪刀」在不同房間時你也獲勝。', pairs: 'rock,scissors' }, 
  { id: 'scissors', name: '剪刀 (Scissors)', team: 'grey', icon: '✂️', desc: '遊戲結束時，自己和「布」在同一個房間，「石頭」在不同房間時你也獲勝。', pairs: 'rock,paper' }, 
  { id: 'sniper', name: '狙擊手 (Sniper)', team: 'grey', icon: '🔭', desc: '在遊戲結束公開玩家角色卡牌前，『公開角色』並指定一名玩家開槍，若擊中「目標」則你也獲勝。', pairs: 'target,decoy' }, 
  { id: 'target', name: '目標 (Target)', team: 'grey', icon: '🎯', desc: '在遊戲結束公開玩家角色卡牌前，若「狙擊手」沒有打中你，則你也獲勝。', pairs: 'sniper,decoy' }, 
  { id: 'decoy', name: '誘餌 (Decoy)', team: 'grey', icon: '🦆', desc: '在遊戲結束公開玩家角色卡牌前，若「狙擊手」開槍打中你，則你也獲勝！', pairs: 'sniper,target' }, 

  // 灰隊特殊勝利類 (Grey)
  { id: 'clone', name: '複製人 (Clone)', team: 'grey', icon: '🧬', desc: '複製第一位與你進行『角色分享』或『顏色分享』者的勝利條件。', pairs: 'robot' },
  { id: 'robot', name: '機器人 (Robot)', team: 'grey', icon: '🤖', desc: '第一位與你進行『角色分享』或『顏色分享』的人若失敗，則你也獲勝。', pairs: 'clone' },
  { id: 'frotteur', name: '性騷擾者 (Frotteur)', team: 'grey', icon: '🖐️', desc: '遊戲結束前必須觸碰過全場每一位玩家即可獨自獲勝，若被「保守人士」抓住手腕則直接失敗。', pairs: 'prude' },
  { id: 'prude', name: '保守人士 (Prude)', team: 'grey', icon: '🚫', desc: '每回合只能使用一次，抓住對方手腕即可強制與對方進行「角色分享」；若對方為「性騷擾者」持續抓住對方的手腕直到回合結束則你也獲勝，若對方不是「性騷擾者」則你失敗。', pairs: 'frotteur' },
  { id: 'anarchist', name: '無政府主義者 (Anarchist)', team: 'grey', icon: '🏴', desc: '進行五輪回合需篡位三次，三輪需篡位兩次成功的話你也獲勝。', pairs: 'minion,mastermind' },
  { id: 'minion', name: '僕從 (Minion)', team: 'grey', icon: '🙇', desc: '遊戲結束時，與你在同一個房間的領隊從來沒有被篡位過則你也獲勝。', pairs: 'anarchist,mastermind' },
  { id: 'mastermind', name: '策劃者 (Mastermind)', team: 'grey', icon: '♟️', desc: '遊戲結束時你是一個房間領隊，且曾做過對面房間領隊則你也獲勝。', pairs: 'anarchist,minion' },
  { id: 'traveler', name: '旅行家 (Traveler)', team: 'grey', icon: '🧳', desc: '遊戲中被當作人質交換達到指定次數（3輪需交換2次，5輪需交換3次）則你也獲勝。' },
  { id: 'judge', name: '法官 (Judge)', team: 'grey', icon: '⚖️', desc: '你與任何人進行『角色分享』或『顏色分享』時，可以給他們"陪審團"狀態：當藍隊/紅隊平手時，可以根據兩隊"陪審團"人數決定勝負。若"陪審團"數量大於總人數1/2(無條件捨棄小數點)，則「法官」也一起獲勝；若藍隊/紅隊"陪審團"數量也平手且超過總人數1/2，則「法官」獨自獲勝。' },
  { id: 'nuclear', name: '核磁暴君 (Nuclear Tyrant)', team: 'grey', icon: '☣️', desc: '你不能拒絕其他玩家的『角色分享』與『顏色分享』。結算時若你沒有和「總統」與「炸彈客」進行過『角色分享』則你獨自獲勝！' },
  { id: 'mi6', name: '秘密情報局 (MI6)', team: 'grey', icon: '🕴️', desc: '在遊戲結束時，你有跟「炸彈客」及「總統」都進行過『角色分享』則你也獲勝。' },
  { id: 'hot_potato', name: '燙手山芋 (Hot Potato)', team: 'grey', icon: '🥔', desc: '你和任何人進行『角色分享』或『顏色分享』，必須立即與你交換角色卡牌，在遊戲結束時仍是「燙手山芋」則強制失敗。' },
  { id: 'agoraphobe', name: '懼曠症患者 (Agoraphobe)', team: 'grey', icon: '🏠', desc: '在遊戲結束時，自己從來沒有離開過初始的房間時則你也獲勝。' },
  { id: 'born_leader', name: '天生領袖 (Born Leader)', team: 'grey', icon: '👑', desc: '遊戲結束時，若你身為所在房間的現任領袖則你也獲勝。' },
  { id: 'telepath', name: '心靈感應者 (Telepath)', team: 'grey', icon: '🔮', desc: '你可以『公開角色』，每回合結束前，猜測進入本房間的人質玩家是誰，猜中則你也獲勝。' },
  //{ id: 'changer', name: '幻形者 (Changer)', team: 'grey', icon: '🤹', desc: '遊戲中必須將卡牌隨機換成歡樂牌庫(沒用到的角色)中的一張牌，以新牌目標結算。' },
  //{ id: 'grey_team', name: '灰隊成員 (Grey Team)', team: 'grey', icon: '⚪', desc: '。' },
  { id: 'director', name: '導演 (Director)', team: 'grey', icon: '🎥', desc: '在遊戲結束公開玩家角色卡牌前，依序點名猜測全場每一位玩家的卡牌顏色，全對則你獨自獲勝。' },
  { id: 'gambler', name: '賭徒 (Gambler)', team: 'grey', icon: '🎰', desc: '在遊戲結束後公開玩家角色卡牌前，猜測哪一隊獲勝（紅/藍/無），猜對獲勝。' },
  { id: 'dog_owner', name: '狗狗主人 (Dog Owner)', team: 'grey', icon: '🐕‍🦺', desc: '你必須找到遺失的「狗狗」。你的勝利條件與你第一個進行『角色分享』的「狗狗」其所屬的陣營一樣。「狗狗」可以在你耳邊說悄悄話溝通，對其他玩家仍要用[汪!]來溝通。', pairs: 'doggy_b,doggy_r' },
  { id: 'secret_police', name: '秘密警察 (Secret Police)', team: 'grey', icon: '🚨', desc: '如果你抓到有人進行任何作弊行為，『公開角色』並大喊[你作弊！！！]並描述情況給同房間的其他玩家聽！若說服大家則你也獲勝。' },

  // 特殊陣營 (Purple,Green,Brown,Black,Yellow,Pink,White)
  { id: 'cult_leader', name: '邪教教主 (Cult Leader)', team: 'purple', icon: '🛐', desc: '每當你與一名玩家進行『角色分享』，該玩家獲得"信徒"狀態。遊戲結束時，若「邪教教主」曾與「猶格·索托斯」進行過『角色分享』，且信徒人數超過總人數1/3(無條件捨棄小數點)，全體"信徒"與「邪教教主」獲得共同勝利。', pairs: 'yog_sothoth' },
  { id: 'yog_sothoth', name: '猶格·索托斯 (Yog Sothoth)', team: 'purple', icon: '🌌', desc: '你是一名地位極其崇高且神祕的邪神！若你在遊戲中與"信徒"進行過『角色分享』，且你從來沒有和「邪教教主」進行過『角色分享』，即可帶著該名"信徒"玩家找到房主終止遊戲，你直接獨自獲勝。', pairs: 'cult_leader' },
  { id: 'illuminati', name: '光明會 (Illuminati)', team: 'orange', icon: '🪙', desc: '每當你與一名玩家進行『角色分享』，該玩家獲得"會員"狀態：可自由選擇要不要幫助「光明會」，"會員"仍可以維持原角色勝利條件。遊戲結束時，若房間領袖都是"會員"，且「光明會」沒有與「私家偵探」進行過『角色分享』，則世界又被暗中掌控，全體"會員"與「光明會」獲得共同勝利。', pairs: 'private_investigator' },
  { id: 'private_investigator', name: '私家偵探 (Private Investigator)', team: 'orange', icon: '🔍', desc: '你是一名調查地下權力的偵探！每回合只能用一次，可找一名玩家進行『角色揭露』，強制對方與你進行『角色分享』。當你在遊戲中與"會員"進行『角色分享』時可以詢問一個是非題，對方必須誠實作答；若與「光明會」進行過『角色分享』，則你也獲勝', pairs: 'illuminati' },
  { id: 'zombie', name: '殭屍 (Zombie)', team: 'green', icon: '🧟', desc: '任何與你進行『角色分享』或『顏色分享』者皆感染"殭屍"狀態！全體存活玩家皆變成"殭屍"即獲勝。' },
  //{ id: 'amnesiac', name: '失憶症患者 (Amnesiac)', team: 'brown', icon: '😵', desc: ' 。' },
  { id: 'drunk', name: '酒鬼 (Drunk)', team: 'brown', icon: '🍺', desc: '在最後一回合開始時，你可以跟本局遊戲的埋葬卡互換，並繼承角色卡牌與勝利條件。' },
  { id: 'leprechaun', name: '小妖精 (Leprechaun)', team: 'yellow', icon: '✨', desc: '你不能拒絕其他玩家的『角色分享』或『顏色分享』；進行任何分享後必須和對方互換卡片，終局還持有小妖精者也獲勝。' },
  //{ id: 'yellow_mem', name: '黃隊成員 (Yellow Team)', team: 'yellow', icon: '🟡', desc: '任何與你進行『角色分享』者皆加入"黃隊"！在遊戲結束時，和「總統」在同一個房間則"黃隊"勝，若「炸彈客」也在同一個房間則藍黃紅隊皆敗。' },
  { id: 'easter_bunny', name: '復活節兔 (Easter Bunny)', team: 'pink', icon: '🐰', desc: '遊戲開始時暫停倒數且所有玩家離開房間，你需要在兩間房間內各藏一個寶物，若所有玩家未能在遊戲結束前找到兩個寶藏，則你獨自獲勝。' },
  { id: 'mr_black', name: '黑先生 (Mr.Black)', team: 'black', icon: '👤', desc: '每回合偷偷將所處房間的燈關掉，沒人發現則你獨自獲勝。' },
  { id: 'beholder', name: '眼魔 (Beholder)', team: 'black', icon: '👁️‍🗨', desc: '你一旦看見任何玩家的卡面，大聲喊出他的角色即可獨自勝利。你也可以『公開角色』，獲得免疫所有角色技能的能力，開始在兩個房間中四處巡視。' },
  //{ id: 'white_team', name: '白隊成員 (White Team)', team: 'white', icon: '⚪', desc: '在最後一回合結束前，必須將自己的卡片換為「紅隊成員」或「藍隊成員」。' },
  { id: 'white_paper', name: '白紙 (White Paper)', team: 'white', icon: '📃', desc: '...' }
];
